export enum Event {
  PROPOSAL_STATUS_ACTION_EXECUTED = 'PROPOSAL_STATUS_ACTION_EXECUTED',
  PROPOSAL_ACCEPTED = 'PROPOSAL_ACCEPTED',
  PROPOSAL_UPDATED = 'PROPOSAL_UPDATED',
  VISIT_CREATED = 'VISIT_CREATED',
  VISIT_DELETED = 'VISIT_DELETED',
}
